export const USER_LIST_ACTION_TYPE = {
  USER_LIST_LOAD_PENDING: 'USER_LIST_ACTION_TYPE.USER_LIST_LOAD_PENDING',
  USER_LIST_LOAD_SUCCESS: 'USER_LIST_ACTION_TYPE.USER_LIST_LOAD_SUCCESS',
  USER_LIST_LOAD_ERROR: 'USER_LIST_ACTION_TYPE.USER_LIST_LOAD_ERROR',
  USER_LIST_SET_DATA: 'USER_LIST_ACTION_TYPE.USER_LIST_SET_DATA',
};
